apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: fintlabs-no
resources:
  - ../../../base
commonLabels:
  app.kubernetes.io/name: fint-kontroll-user-factory
  app.kubernetes.io/instance: fint-kontroll-user-factory_fintlabs-no
  app.kubernetes.io/version: latest
  app.kubernetes.io/component: backend
  app.kubernetes.io/part-of: fint-kontroll
  fintlabs.no/team: bas
  fintlabs.no/org-id: fintlabs.no
patches:
  - patch: |-
      - op: replace
        path: "/spec/acls/0/topic"
        value: "fintlabs-no.kontroll.*"
    target:
      kind: KafkaUserAndAcl
      name: fint-kontroll-user-factory

