apiVersion: fintlabs.no/v1alpha1
kind: Application
metadata:
  name: fint-kontroll-user-factory
  namespace: fintlabs-no
spec:
<<<<<<< Updated upstream
  orgId: orgid
  image: ghcr.io/fintlabs/fint-kontroll-user-factory:latest
  imagePullPolicy: Always
  env:
    - name: fint.kontroll.user.publishing.initial-delay
      value: '20000'
    - name: fint.kontroll.user.publishing.initial-delay-elev
      value: '30000'
    - name: fint.kontroll.user.publishing.fixed-delay
      value: '300000'
    - name: spring.kafka.consumer.group-id
      value: 'fint-kontroll-user-factory'
    - name: JAVA_TOOL_OPTIONS
      value: "-XX:+ExitOnOutOfMemoryError -Xmx896m -verbose:gc"
    - name: fint.kontroll.user.days-before-start-employee
      value: '0'
    - name: fint.kontroll.user.days-before-start-student
      value: '0'
=======
  orgId: fintlabs.no
  image: ghcr.io/fintlabs/fint-kontroll-user-factory:latest
  imagePullPolicy: Always
  env:
    - name: fint.client.base-url
      value: 'http://fint-kontroll-mock-service:3000'
    - name: fint.kontroll.datainput
      value: 'mock'
    - name: fint.resource-gateway.authorization
      value: 'disabled'
>>>>>>> Stashed changes
  kafka:
    enabled: true
    acls:
      - topic: 'fintlabs-no.kontroll.*'
        permission: read
      - topic: 'fintlabs-no.kontroll.*'
        permission: admin
