apiVersion: fintlabs.no/v1alpha1
kind: Application
metadata:
  name: fint-kontroll-user-factory
  namespace: fintlabs-no
spec:
  orgId: fintlabs.no
  image: ghcr.io/fintlabs/fint-kontroll-user-factory:latest
  imagePullPolicy: Always
  env:
    - name: fint.kontroll.user.publishing.initial-delay
      value: '20000'
    - name: fint.kontroll.user.publishing.initial-delay-elev
      value: '25000'
    - name: fint.kontroll.user.publishing.fixed-delay
      value: '20000'
  kafka:
    enabled: true
    acls:
      - topic: 'fintlabs-no.kontroll.*'
        permission: read
      - topic: 'fintlabs-no.kontroll.*'
        permission: admin
